"""Cross-package import gate (PS-140) for scitex-scholar.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.

generated-by: scitex-dev 0.58.1

A GATE NOBODY CAN DATE IS A CLAIM ABOUT AN UNKNOWN PAST. This
list is a snapshot of the cross-package imports as they stood
when the stamp above was written; it does not update itself, and
a stale copy looks exactly like a current one. Measured
2026-08-16: 17 gates across the fleet carried NO stamp and named
a generator that never existed as a command -- the real writer
was a one-shot script since deleted -- so the only way to tell a
fossil from a live gate was a filesystem sweep of mtimes. The
same disease had already been found in the audit gate (68 of 70
still calling audit_all_for_package() with no path=), and the
same cure applies: say which version wrote you.

Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-scholar --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).

Hand-written cases go BELOW the second sentinel. Everything there
is preserved byte-identically across regeneration; everything
between the sentinels is overwritten.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex',
    'scitex.notify',
    'scitex.utils._email',
    'scitex_app',
    'scitex_app._django',
    'scitex_app.embed',
    'scitex_browser',
    'scitex_browser.automation',
    'scitex_browser.core',
    'scitex_browser.debugging',
    'scitex_browser.interaction',
    'scitex_browser.pdf',
    'scitex_browser.stealth',
    'scitex_clew',
    'scitex_config',
    'scitex_dev',
    'scitex_dev._cli._completion',
    'scitex_dev.store',
    'scitex_dict',
    'scitex_io',
    'scitex_logging',
    'scitex_plt',
    'scitex_session',
    'scitex_ui',
]
# ===== END AUTO-GENERATED =====


def _import_or_skip_if_absent(module_name):
    """Import ``module_name``; skip when it (or its backing peer) is absent.

    ``ModuleNotFoundError`` means the peer standalone simply is not
    installed in this environment (or the auto-generated snapshot names a
    path that has since moved) — that is absence, not a regression, so we
    skip. An ``ImportError`` carrying an install hint is the documented
    "optional backing peer absent" signal an alias module raises by design
    (e.g. ``scitex_plt`` re-raises ``"... requires the 'figrecipe'
    package. Install with: pip install figrecipe"`` when figrecipe is not
    present) — same category as absence, so we skip on that signature too.

    Any other failure — a plain ``ImportError`` from a module that exists
    but references a missing symbol, an ``AttributeError``, a syntax error
    — is a genuine rename/move breakage and propagates. That is the gate
    this test exists to guard.
    """
    try:
        return importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        pytest.skip(
            f"{module_name}: not installed in this environment "
            f"(optional peer absent / auto-gen snapshot drift): {exc}"
        )
    except ImportError as exc:
        msg = str(exc)
        if (
            "Install with" in msg
            or "is required for" in msg
            or "install" in msg.lower()
        ):
            pytest.skip(
                f"{module_name}: optional backing peer absent "
                f"(alias raised its install hint): {exc}"
            )
        raise


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_loads(module_name):
    """A declared cross-package module imports cleanly when it is present.

    Asserts the module loaded (``mod is not None``) rather than
    ``mod.__name__ == module_name``: intentional ``sys.modules`` aliases
    (``scitex_plt`` -> ``figrecipe``, ``scitex.gen`` -> ``scitex_gen``)
    legitimately report a different ``__name__`` than the import string.
    """
    # Arrange: module_name is supplied by the parametrize list above.
    # Act
    mod = _import_or_skip_if_absent(module_name)
    # Assert: import_module returns the loaded module (never None on success).
    assert mod is not None
