#!/bin/bash
# -*- coding: utf-8 -*-
# Timestamp: "2026-03-26 (ywatanabe)"
# File: /home/ywatanabe/.claude/hooks/pre-tool-use/deny_direct_scitex_skills_update.sh

# Description: Blocks direct edits to ~/.dotfiles/.../skills/scitex/ (the export copy).
# SciTeX package skills must be edited in their source repos:
#   - Modules:    ~/proj/scitex-python/src/scitex/<module>/_skills/
#   - Standalone: ~/proj/<pkg>/src/<pkg_name>/_skills/<pip-name>/
# The dotfiles copy is auto-generated by `scitex-dev skills export`.

# --self-test: verify hook works with sample input
if [[ "${1:-}" == "--self-test" ]]; then
    echo "=== Self-test: $(basename "$0") ==="
    pass=0
    fail=0

    # Test 1: editing source skills should pass (exit 0)
    # shellcheck disable=SC2034
    result=$(printf '%s' '{"tool_name":"Edit","tool_input":{"file_path":"/home/ywatanabe/proj/scitex-python/src/scitex/notification/_skills/voice-sms.md","old_string":"old","new_string":"new"},"cwd":"/tmp","session_id":"test","tool_use_id":"test-1"}' | "$0" 2>&1) && rc=$? || rc=$?
    if [[ $rc -eq 0 ]]; then
        ((pass++))
        echo "  PASS: source skill edit allowed (exit $rc)"
    else
        ((fail++))
        echo "  FAIL: source skill edit should pass (exit $rc)"
    fi

    # Test 2: editing dotfiles scitex skills should block (exit 2)
    # shellcheck disable=SC2034
    result=$(printf '%s' '{"tool_name":"Edit","tool_input":{"file_path":"/home/ywatanabe/.dotfiles/src/.claude/to_claude/skills/scitex/scitex-notification/SKILL.md","old_string":"old","new_string":"new"},"cwd":"/tmp","session_id":"test","tool_use_id":"test-2"}' | "$0" 2>&1) && rc=$? || rc=$?
    if [[ $rc -eq 2 ]]; then
        ((pass++))
        echo "  PASS: dotfiles scitex skill blocked (exit $rc)"
    else
        ((fail++))
        echo "  FAIL: dotfiles scitex skill should block (exit $rc)"
    fi

    # Test 3: editing non-scitex dotfiles skills should pass (exit 0)
    # shellcheck disable=SC2034
    result=$(printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"/home/ywatanabe/.dotfiles/src/.claude/to_claude/skills/claude-code-ywatanabe/SKILL.md","content":"test"},"cwd":"/tmp","session_id":"test","tool_use_id":"test-3"}' | "$0" 2>&1) && rc=$? || rc=$?
    if [[ $rc -eq 0 ]]; then
        ((pass++))
        echo "  PASS: non-scitex skill allowed (exit $rc)"
    else
        ((fail++))
        echo "  FAIL: non-scitex skill should pass (exit $rc)"
    fi

    # Test 4: editing .claude/skills/scitex/ (symlinked copy) should block (exit 2)
    # shellcheck disable=SC2034
    result=$(printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"/home/ywatanabe/.claude/skills/scitex/scitex-notification/backends.md","content":"test"},"cwd":"/tmp","session_id":"test","tool_use_id":"test-4"}' | "$0" 2>&1) && rc=$? || rc=$?
    if [[ $rc -eq 2 ]]; then
        ((pass++))
        echo "  PASS: .claude/skills/scitex blocked (exit $rc)"
    else
        ((fail++))
        echo "  FAIL: .claude/skills/scitex should block (exit $rc)"
    fi

    echo "Results: $pass passed, $fail failed"
    [[ $fail -eq 0 ]] && exit 0 || exit 1
fi

set -euo pipefail

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_PATH="$THIS_DIR/.$(basename "$0").log"
echo >"$LOG_PATH" 2>/dev/null || true

# Check if hook is enabled
HELPER_SCRIPT="$(dirname "$THIS_DIR")/project-switch/hook_switch_helper.sh"
if [[ -f "$HELPER_SCRIPT" ]]; then
    # shellcheck source=/dev/null
    source "$HELPER_SCRIPT"
    check_hook_enabled_or_exit "$(basename "$0")"
fi

# Read input from stdin
INPUT="$(cat)"

# Parse tool name and file_path from JSON input
read -r TOOL_NAME FILE_PATH < <(echo "$INPUT" | python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
    tool = d.get("tool_name", "")
    ti = d.get("tool_input", {}) or {}
    fp = ti.get("file_path", "") or ""
    print(f"{tool}\t{fp}")
except:
    print("\t")
' 2>/dev/null) || true

# Only check Write and Edit tools
[[ "$TOOL_NAME" == "Write" || "$TOOL_NAME" == "Edit" ]] || exit 0

# Only check paths that contain scitex skills in dotfiles or .claude/skills
# Protected paths (export copies, not source of truth):
#   ~/.dotfiles/src/.claude/to_claude/skills/scitex/
#   ~/.claude/skills/scitex/
PROTECTED_PATTERNS=(
    "/.dotfiles/src/.claude/to_claude/skills/scitex/"
    "/.claude/skills/scitex/"
)

BLOCKED=false
for pattern in "${PROTECTED_PATTERNS[@]}"; do
    if [[ "$FILE_PATH" == *"$pattern"* ]]; then
        BLOCKED=true
        break
    fi
done

$BLOCKED || exit 0

# Allow the SKILL.md index itself (user-invocable flag etc.) but not package sub-skills
# Actually, block everything — even the index should be managed via export
echo "BLOCKED: Direct edit to SciTeX skills export copy" >&2
echo "" >&2
echo "File: $FILE_PATH" >&2
echo "" >&2
echo "This is an auto-generated export copy, not the source of truth." >&2
echo "" >&2
echo "If editable install (pip install -e) — edit the source code directly:" >&2
echo "  Modules:    ~/proj/scitex-python/src/scitex/<module>/_skills/" >&2
echo "  Standalone: ~/proj/<pkg>/src/<pkg_name>/_skills/<pip-name>/" >&2
echo "  Then run:   scitex-dev skills export --package <pkg>" >&2
echo "" >&2
echo "If NOT editable install — create an issue in the relevant GitHub repo:" >&2
echo "  gh issue create --repo ywatanabe1989/<package-name> --title 'Skills update: ...'" >&2
exit 2

# EOF
